const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Dictionary,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Behaviors.Flash,
		C3.Plugins.Spritefont2,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Array: 0},
	{Touch: 0},
	{Browser: 0},
	{AJAX: 0},
	{Mouse: 0},
	{Text: 0},
	{Keyboard: 0},
	{Audio: 0},
	{Dictionary: 0},
	{sayi: 0},
	{alindi: 0},
	{Bullet: 0},
	{Pin: 0},
	{box: 0},
	{sayiTxt: 0},
	{Sprite: 0},
	{box2: 0},
	{Sprite2: 0},
	{TiledBackground: 0},
	{foklift: 0},
	{Rotate: 0},
	{tekerler: 0},
	{secenek: 0},
	{label: 0},
	{Sprite3: 0},
	{Flash: 0},
	{lazerGate: 0},
	{SpriteFont: 0},
	{ritmiksaymaBasligi: 0},
	{ikiser: 0},
	{ucer: 0},
	{dorder: 0},
	{Sprite4: 0},
	{puan: 0},
	{PuanTexT: 0},
	{tekrar: 0},
	{Sprite5: 0},
	{cizgi: 0},
	{baslaButonu: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{dikkatText: 0},
	{kacarkacarText: 0},
	{kacarKacar: 0},
	{ikinci: 0},
	{birinci: 0},
	{hiz: 0}
];

self.InstanceType = {
	Array: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	box: class extends self.ISpriteInstance {},
	sayiTxt: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	box2: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	foklift: class extends self.ISpriteInstance {},
	tekerler: class extends self.ISpriteInstance {},
	secenek: class extends self.ISpriteInstance {},
	label: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	lazerGate: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	ritmiksaymaBasligi: class extends self.ISpriteInstance {},
	ikiser: class extends self.ISpriteInstance {},
	ucer: class extends self.ISpriteInstance {},
	dorder: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	puan: class extends self.ISpriteInstance {},
	PuanTexT: class extends self.ITextInstance {},
	tekrar: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	cizgi: class extends self.ISpriteInstance {},
	baslaButonu: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	dikkatText: class extends self.ITextInstance {},
	kacarkacarText: class extends self.ITextInstance {}
}